INSERT INTO DEVICES (ID,CONFIGURATION,TOPIC_ROOT,TYPE_ID) VALUES (2,'gps=''/rv56/gps'' osmZoomLevel=21 osmTileServerUrl=''http://khm0.googleapis.com/kh?v=192&hl=en-US&x=%2$s&y=%3$s&z=%1$s&token=108840''','/rv56/camera',1);
INSERT INTO MAPPING_ATTRIBUTES (CONNECTED_TO_AUTOPILOT,VV_VISIBLE,TOPIC_ID,DEVICE_ID,SENSORDEFINITION_ID) VALUES (1,0,1,2,5);
INSERT INTO MAPPING_ATTRIBUTES (CONNECTED_TO_AUTOPILOT,VV_VISIBLE,TOPIC_ID,DEVICE_ID,SENSORDEFINITION_ID) VALUES (1,0,2,2,5);
