

INSERT INTO DEVICES (ID,CONFIGURATION,TOPIC_ROOT,TYPE_ID) VALUES (1,'position=(47.821922,13.040811,0)','/gs01/gps',10);
INSERT INTO MAPPING_ATTRIBUTES (CONNECTED_TO_AUTOPILOT,VV_VISIBLE,TOPIC_ID,DEVICE_ID,SENSORDEFINITION_ID) VALUES (1,1,12,1,9);

INSERT INTO PARAMETERS (ID,NAME,SORT,VALUE) VALUES (1,'realVehicleName',0,'GS01');
INSERT INTO PARAMETERS (ID,NAME,SORT,VALUE) VALUES (2,'masterServerURI',0,'http://localhost:13000');
INSERT INTO PARAMETERS (ID,NAME,SORT,VALUE) VALUES (3,'useInternalRosCore',0,'true');

-- UPDATE real_vehicles SET last_update = SYSDATE WHERE name = 'GS01';
