
INSERT INTO DEVICES (ID,CONFIGURATION,TOPIC_ROOT,TYPE_ID)
VALUES (9,'gps=''/quad06/gps'' osmZoomLevel=21 osmTileServerUrl=''http://khm0.googleapis.com/kh?v=192&hl=en-US&x=%2$s&y=%3$s&z=%1$s&token=108840''','/quad06/camera',1);

INSERT INTO MAPPING_ATTRIBUTES (CONNECTED_TO_AUTOPILOT,VV_VISIBLE,TOPIC_ID,DEVICE_ID,SENSORDEFINITION_ID) VALUES (0,0,2,9,null);
INSERT INTO MAPPING_ATTRIBUTES (CONNECTED_TO_AUTOPILOT,VV_VISIBLE,TOPIC_ID,DEVICE_ID,SENSORDEFINITION_ID) VALUES (0,1,1,9,5);
